// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMUhpaWQEEFcvnI-3DYhQDOW-eAIJONsc',
    appId: '1:81063252924:web:4cc96e8ac59042b2ba11b9',
    messagingSenderId: '81063252924',
    projectId: 'sharesoft-4bd13',
    authDomain: 'sharesoft-4bd13.firebaseapp.com',
    storageBucket: 'sharesoft-4bd13.firebasestorage.app',
    measurementId: 'G-4C1Y7XKDH2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtqiipySV4-BaT0JUpfIo524tW10yt5XM',
    appId: '1:81063252924:android:2d3ddb479c906e7dba11b9',
    messagingSenderId: '81063252924',
    projectId: 'sharesoft-4bd13',
    storageBucket: 'sharesoft-4bd13.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAuFfhd3UOVQFph7KKQyEyQUNCXsmZy45I',
    appId: '1:81063252924:ios:9c1fa5f64f2dd13aba11b9',
    messagingSenderId: '81063252924',
    projectId: 'sharesoft-4bd13',
    storageBucket: 'sharesoft-4bd13.firebasestorage.app',
    iosBundleId: 'com.example.shersoft',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAuFfhd3UOVQFph7KKQyEyQUNCXsmZy45I',
    appId: '1:81063252924:ios:9c1fa5f64f2dd13aba11b9',
    messagingSenderId: '81063252924',
    projectId: 'sharesoft-4bd13',
    storageBucket: 'sharesoft-4bd13.firebasestorage.app',
    iosBundleId: 'com.example.shersoft',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMUhpaWQEEFcvnI-3DYhQDOW-eAIJONsc',
    appId: '1:81063252924:web:cce4881701721648ba11b9',
    messagingSenderId: '81063252924',
    projectId: 'sharesoft-4bd13',
    authDomain: 'sharesoft-4bd13.firebaseapp.com',
    storageBucket: 'sharesoft-4bd13.firebasestorage.app',
    measurementId: 'G-9K5JV0RS81',
  );
}
